---
title: "Lab2"
author: "Ross Ellingboe"
date: "2/5/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Team Memebers: Ross Ellingboe
Group 5

Github Repo: https://github.com/ellingboe17/Lab2

## Group Question Set #1
1. The number of chocolate bars reviewed was 1852
2. Rating numbers slowly increased until 2016 then had a declining rate into present time. 

```
library(ggplot2)
choco <- read.cvs("https://ds202-at-isu.github.io/labs/data/choco.csv")
head(choco)
ggplot(aes(x = Review.Date),data = choco) + geom_bar()
```


## Individual Questions Set #2
1. The distribution is symmertrical and unimodal with outliers at 5, 1 and 1.5. The median is approx. 3. 

```
ggplot(data = choco, aes(x = Rating)) +
  geom_histogram(binwidth = .25)
```
  
2. There is no significant rating impact of the chocolae due to cocoa percentage. 

- The only five star rating had a cocoa percentage of 70%
- A chocolate that recieved a one star ratings had a cocoa percentage of 70%

```
ggplot(aes(x=Rating, y = Cocoa.Pct), data = choco) + geom_point()
```


3. The United State has a vast amount of ratings compared to other countries, over 5x greater. 

```
Top3<- dplyr::filter(choco, Company.Location %in% c("U.S.A.", "France", "Canada"))
ggplot(data=Top3, aes(x=Company.Location))+geom_bar()
```


## Paragraph
I was absent and did this assignment by myself, but github provides great group work features enabling everyone to work at once. 